/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddNewRouteImport } from './routes/add-new'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DirectoryRouteImport } from './routes/directory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddNewRoute = AddNewRouteImport.update({
  id: '/add-new',
  path: '/add-new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-new': typeof AddNewRoute
  '/auth': typeof AuthRoute
  '/directory': typeof DirectoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-new': typeof AddNewRoute
  '/auth': typeof AuthRoute
  '/directory': typeof DirectoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-new': typeof AddNewRoute
  '/auth': typeof AuthRoute
  '/directory': typeof DirectoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-new' | '/auth' | '/directory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-new' | '/auth' | '/directory'
  id: '__root__' | '/' | '/add-new' | '/auth' | '/directory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddNewRoute: typeof AddNewRoute
  AuthRoute: typeof AuthRoute
  DirectoryRoute: typeof DirectoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-new': {
      id: '/add-new'
      path: '/add-new'
      fullPath: '/add-new'
      preLoaderRoute: typeof AddNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddNewRoute: AddNewRoute,
  AuthRoute: AuthRoute,
  DirectoryRoute: DirectoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
